### ISSUE TITLE
Can't open ndpi file

### ISSUE THREAD

**Issue by asmagen** [DigitalSlideArchive/HistomicsTK#830]
I installed all the required packages properly but can't get to open any ndpi file:

```>>> ts = large_image.getTileSource('Li63T_CD3.ndpi')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/large_image/tilesource/__init__.py", line 79, in getTileSource
    return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/large_image/tilesource/__init__.py", line 67, in getTileSourceFromDict
    raise TileSourceException('No available tilesource for %s' % pathOrUri)
large_image.exceptions.TileSourceException: No available tilesource for Li63T_CD3.ndpi```

**Comment by dgutman** [comment]
Can you paste your pip install or where you copied it from?
