### ISSUE TITLE
After Windows 10 installs your github tutorial successfully, an import error occurs

### ISSUE THREAD

**Issue by 464hee** [DigitalSlideArchive/HistomicsTK#961]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\seg_pred\1.py", line 1, in <module>
    import  histomicstk
  File "C:\Users\Administrator\HistomicsTK\histomicstk\__init__.py", line 2, in <module>
    from . import segmentation  # must be imported before features
  File "C:\Users\Administrator\HistomicsTK\histomicstk\segmentation\__init__.py", line 11, in <module>
    from . import label, level_set, nuclear, positive_pixel_count
  File "C:\Users\Administrator\HistomicsTK\histomicstk\segmentation\label\__init__.py", line 18, in <module>
    from .trace_object_boundaries import trace_object_boundaries
  File "C:\Users\Administrator\HistomicsTK\histomicstk\segmentation\label\trace_object_boundaries.py", line 3, in <module>
    from ._trace_object_boundaries_cython import _trace_object_boundaries_cython
ModuleNotFoundError: No module named 'histomicstk.segmentation.label._trace_object_boundaries_cython'

**Comment by 464hee** [comment]
Install the tutorial to perform git clone, so I should use the latest version

**Comment by iflament** [comment]
I'm having the same issue. Has this been resolved?

**Comment by manthey** [comment]
Which tutorial are you following?

**Comment by abehzadnia** [comment]
In case you haven't gotten it to work - I spent the whole day banging my head trying to figure out whats going on in windows 11.
See my post #973 for how I got to work :) - in windows 10 make sure you tick windows 10 sdk

**Comment by 464hee** [comment]
> In case you haven't gotten it to work - I spent the whole day banging my head trying to figure out whats going on in windows 11. See my post #973 for how I got to work :) - in windows 10 make sure you tick windows 10 sdk

Thank you for your work, I will try again
